pipeline {
    agent any
    triggers { 
        upstream(upstreamProjects: 'server', 
                 threshold: hudson.model.Result.SUCCESS) 
    }
    stages {
        stage('build') { 
            steps {
                sh 'bash -c ls -la .' 
            }
        }
        stage('test') { 
            steps {
                sh 'bash -c ls -la .' 
            }
        }
    }
}

