pipeline {
    agent any
    triggers {
        upstream(upstreamProjects: 'CI', 
                 threshold: hudson.model.Result.SUCCESS)
    }
    stages {
        stage('security_tests') { 
            steps {
                input message: "Run security tests?"
                sh 'bash -c ls -la .' 
            }
        }
    }
}
